// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa89T3uYBDQOAWh6or1DxDPHVmuHTaxjw',
    appId: '1:491950626018:web:d6040bd0d0a298f5df3abb',
    messagingSenderId: '491950626018',
    projectId: 'teledoctor-71136',
    authDomain: 'teledoctor-71136.firebaseapp.com',
    storageBucket: 'teledoctor-71136.appspot.com',
    measurementId: 'G-T9QXN53J43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-_yfS3PJteKTaK8IEW_haWEBdUqRbQuo',
    appId: '1:491950626018:android:c37ab5ebcff09ccfdf3abb',
    messagingSenderId: '491950626018',
    projectId: 'teledoctor-71136',
    storageBucket: 'teledoctor-71136.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkjMDTfP69tlDjSBNQhkuA-n3irIyN1iY',
    appId: '1:491950626018:ios:ba43ad79d8674327df3abb',
    messagingSenderId: '491950626018',
    projectId: 'teledoctor-71136',
    storageBucket: 'teledoctor-71136.appspot.com',
    iosBundleId: 'com.example.teleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkjMDTfP69tlDjSBNQhkuA-n3irIyN1iY',
    appId: '1:491950626018:ios:3bc0d4abf3713af1df3abb',
    messagingSenderId: '491950626018',
    projectId: 'teledoctor-71136',
    storageBucket: 'teledoctor-71136.appspot.com',
    iosBundleId: 'com.example.teleApp.RunnerTests',
  );
}
